### ISSUE TITLE
When I scroll on mobile, hamburger flow down.

### ISSUE THREAD

**Issue by tomriddle7** [dieudonneAwa/responsive-navbar#4]
It cause StyledBurger has positon: fixed;
How can I fix it?

**Comment by Deep-Codes** [comment]
In the Burger.jsx

Remove the Position : Fixed ;

`const StyledBurger = styled.div`
  width: 2rem;
  height: 2rem;
  // Remove this 
  // position: fixed;
  top: 15px;
  right: 20px;
  z-index: 20;
  display: none;`

**Comment by Deep-Codes** [comment]
Remove the Position: Fixed property in Burger.jsx File
